"""add notification settings to user

Revision ID: 0de705ade2e6
Revises: 6973855769a3
Create Date: 2026-06-24 14:50:08.645936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de705ade2e6'
down_revision: Union[str, Sequence[str], None] = '6973855769a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify_overdue', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_upcoming', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_upcoming')
    op.drop_column('users', 'notify_overdue')
    # ### end Alembic commands ###
