"""add notification tracking fields

Revision ID: a735012cffb5
Revises: 0de705ade2e6
Create Date: 2026-06-24 15:29:01.852834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a735012cffb5'
down_revision: Union[str, Sequence[str], None] = '0de705ade2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('overdue_notified', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('upcoming_notified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_overdue_enabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('notify_upcoming_enabled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_upcoming_enabled_at')
    op.drop_column('users', 'notify_overdue_enabled_at')
    op.drop_column('tasks', 'upcoming_notified')
    op.drop_column('tasks', 'overdue_notified')
    # ### end Alembic commands ###
